-- ----------------------------------------
-- Datos iniciales para la base de datos. -
-- ----------------------------------------

-- Tabla Medicamentos
INSERT INTO MEDICAMENTOS VALUES(1,'ANTI HIPERTENSIVO', 'Medicamentos para bajar la tensión');
INSERT INTO MEDICAMENTOS VALUES(2,'ANALGESICO', 'Medicamentos para calmar el dolor');
INSERT INTO MEDICAMENTOS VALUES(3,'ANTI CONVULSIVANTE', 'Medicamentos para no convulsionar');
INSERT INTO MEDICAMENTOS VALUES(4,'HIPO GLICEMIANTE ORAL', 'Medicamentos para bajar la glicemia');
INSERT INTO MEDICAMENTOS VALUES(5,'INSULINA', 'Medicamentos para bajar la glicemia');
INSERT INTO MEDICAMENTOS VALUES(6,'ANTIBIOTICO', 'Medicamentos antibioticos');
INSERT INTO MEDICAMENTOS VALUES(7,'ANTICUAGULANTE', 'Medicamentos anticuagulante');

-- Tabla Pacientes
INSERT INTO PACIENTES VALUES(1,'Jose','Schmidt','M');
INSERT INTO PACIENTES VALUES(2,'Pasqual','Troncone','M');
INSERT INTO PACIENTES VALUES(3,'Wilfredo','Rangel','M');
INSERT INTO PACIENTES VALUES(4,'Lorena','Contreras','F');
INSERT INTO PACIENTES VALUES(5,'Vanessa','Contreras','F');
-- ------------------------------------------------------
-- Tabla DOCTORES
INSERT INTO DOCTORES VALUES (1,'CRISTINA','MARTÍ');
INSERT INTO DOCTORES VALUES (2,'VÍCTOR','RODRIGUEZ');
INSERT INTO DOCTORES VALUES (3,'RICARDO','AGUIAR');
-- ------------------------------------------------------

-- Tabla Antecedentes
INSERT INTO ANTECEDENTES VALUES (1,'SIN ANTECEDENTES');
INSERT INTO ANTECEDENTES VALUES (2,'HIPERTENSIVO');
INSERT INTO ANTECEDENTES VALUES (3,'DIABETICO');
INSERT INTO ANTECEDENTES VALUES (4,'INFESCCIÓN RESPIRATORIA');
INSERT INTO ANTECEDENTES VALUES (5,'TRASTORNOS DEL RITMO');

-- Tabla Sintomas_MAESTRA
INSERT INTO SINTOMAS_MAESTRA VALUES('TOS');
INSERT INTO SINTOMAS_MAESTRA VALUES('FIEBRE');
INSERT INTO SINTOMAS_MAESTRA VALUES('DIARREA');
INSERT INTO SINTOMAS_MAESTRA VALUES('DOLOR');
-- ------------------------------------------------------

-- Tabla Motivos_MAESTRA
INSERT INTO MOTIVOS_MAESTRA VALUES('POLITRAUMATISMO SEVERO');
INSERT INTO MOTIVOS_MAESTRA VALUES('NO RESPIRA');
INSERT INTO MOTIVOS_MAESTRA VALUES('SIN PULSO');
INSERT INTO MOTIVOS_MAESTRA VALUES('ENTUBACIÓN PREHOSPITALARIA');
INSERT INTO MOTIVOS_MAESTRA VALUES('PACIENTE QUE NO RESPONDE');
INSERT INTO MOTIVOS_MAESTRA VALUES('DIFICULTAD RESPIRATORIA');
INSERT INTO MOTIVOS_MAESTRA VALUES('TOS');
INSERT INTO MOTIVOS_MAESTRA VALUES('FIEBRE');
INSERT INTO MOTIVOS_MAESTRA VALUES('DIARREA');
INSERT INTO MOTIVOS_MAESTRA VALUES('DOLOR');
INSERT INTO MOTIVOS_MAESTRA VALUES('MALESTAR GENERAL');
-- ---------------------------------------------------------

-- Tabla Categorias_MAESTRA
INSERT INTO CATEGORIAS_MAESTRA VALUES('URGENCIA HIPERTENSIVA',3);
INSERT INTO CATEGORIAS_MAESTRA VALUES('EMERGENCIA HIPERTENSIVA',2);
INSERT INTO CATEGORIAS_MAESTRA VALUES('ENCEFALOPATIA HIPERTENSIVA',1);
INSERT INTO CATEGORIAS_MAESTRA VALUES('EMERGENCIA HIPERTENSIVA CON EDEMA AGUDO DE PULMON',1);
INSERT INTO CATEGORIAS_MAESTRA VALUES('INFARTO AL MIOCARDIO AGUDO',2);
INSERT INTO CATEGORIAS_MAESTRA VALUES('PARO CARDIACO',1);
INSERT INTO CATEGORIAS_MAESTRA VALUES('OTRO SINDROME CORONARIO',2);
INSERT INTO CATEGORIAS_MAESTRA VALUES('ECV',1);
INSERT INTO CATEGORIAS_MAESTRA VALUES('NEUMONIA CON SEPSIS',2);
INSERT INTO CATEGORIAS_MAESTRA VALUES('NEUMONIA',3);
INSERT INTO CATEGORIAS_MAESTRA VALUES('ASMA LEVE',4);
INSERT INTO CATEGORIAS_MAESTRA VALUES('ASMA MODERADA',3);
INSERT INTO CATEGORIAS_MAESTRA VALUES('PRIORIDAD 1',1);
INSERT INTO CATEGORIAS_MAESTRA VALUES('PRIORIDAD 2',2);
INSERT INTO CATEGORIAS_MAESTRA VALUES('PRIORIDAD 3',3);
INSERT INTO CATEGORIAS_MAESTRA VALUES('PRIORIDAD 4',4);
INSERT INTO CATEGORIAS_MAESTRA VALUES('PRIORIDAD 5',5);
-- ------------------------------------------------------------





