-- BLOQUE DE CODIGO QUE CONTIENE:
-- SENTENCIA PARA CREAR EL TABLESPACE DONDE SE ALMACENARA LA BASE DE DATOS DE TRIAJE, CREACIÓN DE USUARIO
-- CREATE USER TRIAJE IDENTIFIED BY "TRIAJE"
-- GRANT CONNECT TO TRIAJE
-- GRANT CREATE TABLESPACE TO TRIAJE
-- CREATE TABLESPACE TRIAJE DATAFILE 'TRIAJED01.DBF' SIZE 500M;

DROP TABLE REFLEJA;
CREATE TABLE REFLEJA(
SIGNO_CODIGO NUMBER(4),
EPISODIO_TRIAJE_CODIGO NUMBER(4)
) TABLESPACE TRIAJE;

DROP TABLE INDICA;
CREATE TABLE INDICA(
CONSTANTE_CODIGO NUMBER(4),
EPISODIO_TRIAJE_CODIGO NUMBER(4)
) TABLESPACE TRIAJE;

DROP TABLE SE_AGRUPAN;
CREATE TABLE SE_AGRUPAN(
SINTOMA_CODIGO NUMBER(4),
EPISODIO_TRIAJE_CODIGO NUMBER(4)
) TABLESPACE TRIAJE;

DROP TABLE EPISODIOS_TRIAJE;
CREATE TABLE EPISODIOS_TRIAJE(
CODIGO NUMBER(4) NOT NULL,
DOCTOR_CODIGO NUMBER(4) NOT NULL,
MOTIVO_URGENCIA_CODIGO NUMBER(4) NOT NULL,
PACIENTE_CODIGO NUMBER(4) NOT NULL,
FECHA_HORA_MINUTO DATE NOT NULL,
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE ALERGICO_A;
CREATE TABLE ALERGICO_A(
PACIENTE_CODIGO NUMBER(4),
ALERGIA_CODIGO NUMBER(4)
) TABLESPACE TRIAJE;

DROP TABLE A_PADECIDO;
CREATE TABLE A_PADECIDO(
PACIENTE_CODIGO NUMBER(4),
ANTECEDENTE_CODIGO NUMBER(4)
) TABLESPACE TRIAJE;

DROP TABLE TOMA;
CREATE TABLE TOMA(
PACIENTE_CODIGO NUMBER(4),
MEDICAMENTO_CODIGO NUMBER(4)
) TABLESPACE TRIAJE;

DROP TABLE SINTOMAS;
CREATE TABLE SINTOMAS(
CODIGO NUMBER(4) NOT NULL,
DESCRIPCION VARCHAR (150),
LOCALIZACION VARCHAR (150) DEFAULT 'NOAPLICA' NOT NULL,
PREGUNTA1 CHAR(2) DEFAULT 'NO' NOT NULL,
PREGUNTA2 CHAR(2) DEFAULT 'NO' NOT NULL,
-- LA DURACIÓN ES UN ATRIBUTO DIFUSO TIPO 2 QUE MIDE CUANTOS MINUTOS LE DURA AL PACIENTE EL SINTOMA 
-- POR CADA REPETICIÓN
DURACIONT NUMBER(4) DEFAULT 0 NOT NULL,
DURACION1 NUMBER(3),
DURACION2 NUMBER(3),
DURACION3 NUMBER(3),
DURACION4 NUMBER(3),
-- LA FECHA DE INICIO ES UN ATRIBUTO DIFUSO TIPO 2, EN LA QUE SE PUEDEN ALMACENAR VALORES COMO
-- HACE POCO, HACE MUCHO, ETC
INICIOT NUMBER(1) DEFAULT 0 NOT NULL,
INICIO1 NUMBER(3),
INICIO2 NUMBER(3),
INICIO3 NUMBER(3),
INICIO4 NUMBER(3),
-- LA REPETICIÓN DEL SINTOMA DEL PACIENTE SE CUENTA POR DÍA, PUEDE TOMAR VALORES COMO POCO, MAS O MENOS, O MUCHO
REPETICIONT NUMBER(1) DEFAULT 1 NOT NULL,
REPETICION1 NUMBER(3),
REPETICION2 NUMBER(3),
REPETICION3 NUMBER(3),
REPETICION4 NUMBER(3),
/* LA ESCALA DE NIVEL ES UN ATRIBUTO DIFUSO TIPO 3, EN EL QUE PODEMOS ALMACENAR VALORES COMO LIGERO, MODERADO, INTENSO
-- ETC.*/
NIVELT NUMBER(1) DEFAULT 0 NOT NULL, -- SOLO HACE FALTA COMPARAR LAS ETIQUETAS, POR LO QUE EXISTEN SOLO 2 COLUMNAS
									 -- PARA LA DEFINICIÓN DEL ATRIBUTO
NIVELP1 NUMBER(3,2), --AQUI ALMACENA CUANTO ES PARECIDO A LA ETIQUETA DE NIVEL
NIVEL1 NUMBER(3),   --AQUI ALMACENA EL ID DE LA ETIQUETA CONTRA LA QUE SE ESTA COMPARANDO
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE SINTOMAS_MAESTRA;
CREATE TABLE SINTOMAS_MAESTRA(
DESCRIPCION VARCHAR2(150),
CONSTRAINT UNICO_SINTOMA UNIQUE (DESCRIPCION)
) TABLESPACE TRIAJE;

DROP TABLE SINTOMAS_LOCALIZACION_MAESTRA;
CREATE TABLE SINTOMAS_LOCALIZACION_MAESTRA(
LOCALIZACION VARCHAR2(150),
CONSTRAINT UNICA_LOCALIZACION UNIQUE (LOCALIZACION)
) TABLESPACE TRIAJE;


DROP TABLE CONSTANTES;
CREATE TABLE CONSTANTES(
CODIGO NUMBER (4) NOT NULL,
-- LA TEMPERATURA ES UN ATRIBUTO DIFUSO TIPO 2, EN EL QUE SE PUEDEN ALMACENAR VALORES COMO BAJA, NORMAL, FIEBRE, ETC
TEMPT NUMBER(1) DEFAULT 0 NOT NULL,
TEMP1 NUMBER(3),
TEMP2 NUMBER(3),
TEMP3 NUMBER(3),
TEMP4 NUMBER(3),
-- LA TENSIÓN ARTERIAL SISTOLICA ES UN ATRIBUTO DIFUSO TIPO 2, ALMACENA VALORES DE MUY BAJA, NORMAL, MUY ALTA
TAST NUMBER(1) DEFAULT 0 NOT NULL,
TAS1 NUMBER(3),
TAS2 NUMBER(3),
TAS3 NUMBER(3),
TAS4 NUMBER(3),
-- LA FRECUENCIA CARDÍACA ES UN ATRIBUTO DIFUSO TIPO 2, ALMACENA VALORES COMO MUY BAJA, NORMAL, ALTA Y MUY ALTA
FCT NUMBER(1) DEFAULT 0 NOT NULL,
FC1 NUMBER(3),
FC2 NUMBER(3),
FC3 NUMBER(3),
FC4 NUMBER(3),
-- LA FRECUENCIA RESPIRATORIA ES UN ATRIBUTO DIFUSO TIPO 2, ALMACENA VALORES COMO MUY BAJA, NORMAL, ALTA Y MUY ALTA
FRT NUMBER(1) DEFAULT 0 NOT NULL,
FR1 NUMBER(3),
FR2 NUMBER(3),
FR3 NUMBER(3),
FR4 NUMBER(3),
-- LA SATURACIÓN DE OXIGENO ES UN ATRIBUTO DIFUSO TIPO 1, PUEDE TOMAR VALORES O ETIQUETAS.
SATO2 NUMBER (3),
-- LA GLICEMIA CAPILAR ES UN ATRIBUTO DIFUSO TIPO 2, PUEDE TOMAR VALORES COMO HIPOGLUCEMIA, NORMAL, ETC.
GLICAPT NUMBER (1) DEFAULT 0 NOT NULL,
GLICAP1 NUMBER(3),
GLICAP2 NUMBER(3),
GLICAP3 NUMBER(3),
GLICAP4 NUMBER(3),
-- EL ESTADO DE CONCIENCIA ES UN ATRIBUTO DIFUSO TIPO 2, PUEDE TOMAR VALORES COMO ALERTA, SOMNOLENCIA, ESTUPOR, ETC
NIHSST NUMBER (1) DEFAULT 0 NOT NULL,
NIHSS1 NUMBER (3),
NIHSS2 NUMBER (3),
NIHSS3 NUMBER (3),
NIHSS4 NUMBER (3),
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE CATEGORIAS;
CREATE TABLE CATEGORIAS(
CODIGO NUMBER (4) NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL,
-- EL TIPO DE CATEGORIA ES UN ATRIBUTO DIFUSO TIPO 3, SE NECESITAN SOLO DOS COLUMNAS PARA DEFINIR ESTE ATRIBUTO
TIPO_CATEGORIAT NUMBER(1) DEFAULT 0 NOT NULL, -- SOLO HACE FALTA COMPARAR LAS ETIQUETAS, POR LO QUE EXISTEN SOLO 2 COLUMNAS
									 -- PARA LA DEFINICIÓN DEL ATRIBUTO
TIPO_CATEGORIAP1 NUMBER (3,2), --AQUI ALMACENA CUANTO ES PARECIDO A LA ETIQUETA DE CATEGORIA
TIPO_CATEGORIA1 NUMBER  (3),   --AQUI ALMACENA EL ID DE LA ETIQUETA CONTRA LA QUE SE ESTA COMPARANDO
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE CATEGORIAS_MAESTRA;
CREATE TABLE CATEGORIAS_MAESTRA(
DESCRIPCION VARCHAR2(150),
NIVEL NUMBER(1),
CONSTRAINT UNICO_CATEGORIA UNIQUE (DESCRIPCION)
) TABLESPACE TRIAJE;

DROP TABLE SIGNOS;
CREATE TABLE SIGNOS(
CODIGO NUMBER (4) NOT NULL,
-- EL TIPO DE PIEL ES UN ATRIBUTO DIFUSO TIPO 3,SE NECESITAN SOLO DOS COLUMNAS PARA DEFINIR ESTE ATRIBUTO
TIPO_PIELT NUMBER(1) DEFAULT 0 NOT NULL, -- SOLO HACE FALTA COMPARAR LAS ETIQUETAS, POR LO QUE EXISTEN SOLO 2 COLUMNAS
									 -- PARA LA DEFINICIÓN DEL ATRIBUTO
TIPO_PIELP1 NUMBER (3,2), --AQUI ALMACENA CUANTO ES PARECIDO A LA ETIQUETA DE TIPO DE PIEL
TIPO_PIEL1 NUMBER  (3),   --AQUI ALMACENA EL ID DE LA ETIQUETA CONTRA LA QUE SE ESTA COMPARANDO
-- EL PULSO RADIAL ES UN ATRIBUTO DIFUSO TIPO 2, MUY POSIBLEMENTE TODOS LOS VALORES CONTRA LOS QUE SE COMPAREN
-- SEAN FUNCIONES L
PULSO_RADIALT NUMBER (1) DEFAULT 0 NOT NULL,
PULSO_RADIAL1 NUMBER (3),
PULSO_RADIAL2 NUMBER (3),
PULSO_RADIAL3 NUMBER (3),
PULSO_RADIAL4 NUMBER (3),
-- EL PULSO ES UN ATRIBUTO DIFUSO TIPO 2, MUY POSIBLEMENTE TODOS LOS VALORES CONTRA LOS QUE SE COMPAREN
-- SEAN FUNCIONES L
PULSOT NUMBER (1) DEFAULT 0 NOT NULL,
PULSO1 NUMBER (3),
PULSO2 NUMBER (3),
PULSO3 NUMBER (3),
PULSO4 NUMBER (3),
-- LA RESPIRACIÓN ES UN ATRIBUTO DIFUSO TIPO 2
RESPIRACIONT NUMBER (1) DEFAULT 0 NOT NULL,
RESPIRACION1 NUMBER(3),
RESPIRACION2 NUMBER(3),
RESPIRACION3 NUMBER(3),
RESPIRACION4 NUMBER(3),
-- FALTA GLASGOW Y TAMBIEN FALTA SOMNOLENCIA O CONFUSIÓN
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE ALERGIAS;
CREATE TABLE ALERGIAS(
CODIGO NUMBER (4) NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL,
TIPO VARCHAR(150) NOT NULL,
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE MOTIVOS_URGENCIA;
CREATE TABLE MOTIVOS_URGENCIA(
CODIGO NUMBER(4) NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL,
-- LA DURACIÓN ES UN ATRIBUTO DIFUSO TIPO 2 QUE MIDE CUANTOS MINUTOS LE DURA AL PACIENTE EL MOTIVO DE URGENCIA 
DURACIONT NUMBER(4) DEFAULT 0 NOT NULL,
DURACION1 NUMBER(3),
DURACION2 NUMBER(3),
DURACION3 NUMBER(3),
DURACION4 NUMBER(3),
-- EL INICIO ES UN ATRIBUTO DIFUSO TIPO 2, EN LA QUE SE PUEDEN ALMACENAR VALORES COMO
-- HACE POCO, HACE MUCHO, ETC
INICIOT NUMBER(1) DEFAULT 0 NOT NULL,
INICIO1 NUMBER(3),
INICIO2 NUMBER(3),
INICIO3 NUMBER(3),
INICIO4 NUMBER(3),
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE MOTIVOS_MAESTRA;
CREATE TABLE MOTIVOS_MAESTRA(
DESCRIPCION VARCHAR2(150),
CONSTRAINT UNICO_MOTIVO UNIQUE (DESCRIPCION)
) TABLESPACE TRIAJE;

DROP TABLE DOCTORES;
CREATE TABLE DOCTORES(
CODIGO NUMBER(4) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE PACIENTES;
CREATE TABLE PACIENTES(
CODIGO NUMBER(4) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
GENERO VARCHAR(1) NOT NULL,
EDAD NUMBER(3) NOT NULL,
-- STATUS PUEDE TENER 3 POSIBLES VALORES 'E' QUE SIGNIFICA 'ESPERANDO', 'T' QUE SIGNIFICA CLASIFICADO EN TRIAJE,Y 'A' QUE SIGNIFICA ATENDIDO.
-- UN PACIENTE ES ATENDIDO CUANDO SALE DE LA COLA DE TRIAJE.
STATUS VARCHAR(1) NOT NULL,
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE MEDICAMENTOS;
CREATE TABLE MEDICAMENTOS(
CODIGO NUMBER(4) NOT NULL,
CATEGORIA CHAR(150) NOT NULL, -- ANTIHIPERTENSIVOS, ANALGESICOS, ETC.
DESCRIPCION CHAR(150) NOT NULL,
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE ANTECEDENTES;
CREATE TABLE ANTECEDENTES(
CODIGO NUMBER(4) NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL, 
PRIMARY KEY (CODIGO)
) TABLESPACE TRIAJE;

DROP TABLE ANTECEDENTES_MAESTRA;
CREATE TABLE ANTECEDENTES_MAESTRA(
DESCRIPCION VARCHAR2(150),
CONSTRAINT UNICO_ANTECEDENTE UNIQUE (DESCRIPCION)
) TABLESPACE TRIAJE;


-- ---------------------------------------------
-- INICIO DE LOS CONSTRAINT POR CLAVE FORANEA. -
-- ---------------------------------------------

ALTER TABLE CATEGORIAS
ADD CONSTRAINT CATEGORIA_MAESTRA_FK
FOREIGN KEY (DESCRIPCION)
REFERENCES CATEGORIAS_MAESTRA(DESCRIPCION);

ALTER TABLE SINTOMAS
ADD CONSTRAINT SINTOMA_MAESTRA_FK
FOREIGN KEY (DESCRIPCION)
REFERENCES SINTOMAS_MAESTRA(DESCRIPCION);

ALTER TABLE SINTOMAS
ADD CONSTRAINT SINTOMA_LOC_MAESTRA_FK
FOREIGN KEY (LOCALIZACION)
REFERENCES SINTOMAS_LOCALIZACION_MAESTRA(LOCALIZACION);

ALTER TABLE MOTIVOS_URGENCIA
ADD CONSTRAINT MOTIVO_MAESTRA_FK
FOREIGN KEY (DESCRIPCION)
REFERENCES MOTIVOS_MAESTRA(DESCRIPCION);

ALTER TABLE EPISODIOS_TRIAJE
ADD CONSTRAINT EPISODIO_DOCTOR_FK
FOREIGN KEY (DOCTOR_CODIGO)
REFERENCES DOCTORES(CODIGO);

ALTER TABLE EPISODIOS_TRIAJE
ADD CONSTRAINT EPISODIO_MOTIVO_FK
FOREIGN KEY (MOTIVO_URGENCIA_CODIGO)
REFERENCES MOTIVOS_URGENCIA(CODIGO);

ALTER TABLE EPISODIOS_TRIAJE
ADD CONSTRAINT EPISODIO_PACIENTE_FK
FOREIGN KEY (PACIENTE_CODIGO)
REFERENCES PACIENTES(CODIGO);

ALTER TABLE REFLEJA
ADD CONSTRAINT REFLEJA_SIGNO_FK
FOREIGN KEY (SIGNO_CODIGO)
REFERENCES SIGNOS(CODIGO);

ALTER TABLE REFLEJA
ADD CONSTRAINT REFLEJA_EPISODIO_FK
FOREIGN KEY (EPISODIO_TRIAJE_CODIGO)
REFERENCES EPISODIOS_TRIAJE(CODIGO);

ALTER TABLE INDICA
ADD CONSTRAINT INDICA_CONSTANTE_FK
FOREIGN KEY (CONSTANTE_CODIGO)
REFERENCES CONSTANTES(CODIGO);

ALTER TABLE INDICA
ADD CONSTRAINT INDICA_EPISODIO_FK
FOREIGN KEY (EPISODIO_TRIAJE_CODIGO)
REFERENCES EPISODIOS_TRIAJE(CODIGO);

ALTER TABLE SE_AGRUPAN
ADD CONSTRAINT SE_AGRUPAN_SINTOMA_FK
FOREIGN KEY (SINTOMA_CODIGO)
REFERENCES SINTOMAS(CODIGO);

ALTER TABLE SE_AGRUPAN
ADD CONSTRAINT SE_AGRUPAN_EPISODIO_FK
FOREIGN KEY (EPISODIO_TRIAJE_CODIGO)
REFERENCES EPISODIOS_TRIAJE(CODIGO);

ALTER TABLE TOMA
ADD CONSTRAINT TOMA_MEDICAMENTO_FK
FOREIGN KEY (MEDICAMENTO_CODIGO)
REFERENCES MEDICAMENTOS(CODIGO);

ALTER TABLE TOMA
ADD CONSTRAINT TOMA_PACIENTE_FK
FOREIGN KEY (PACIENTE_CODIGO)
REFERENCES PACIENTES(CODIGO);

ALTER TABLE A_PADECIDO
ADD CONSTRAINT A_PADECIDO_ANTECEDENTE_FK
FOREIGN KEY (ANTECEDENTE_CODIGO)
REFERENCES ANTECEDENTES(CODIGO);

ALTER TABLE A_PADECIDO
ADD CONSTRAINT A_PADECIDO_PACIENTE_FK
FOREIGN KEY (PACIENTE_CODIGO)
REFERENCES PACIENTES(CODIGO);

ALTER TABLE ALERGICO_A
ADD CONSTRAINT ALERGICO_A_ALERGIA_FK
FOREIGN KEY (ALERGIA_CODIGO)
REFERENCES ALERGIAS(CODIGO);

ALTER TABLE ALERGICO_A
ADD CONSTRAINT ALERGICO_A_PACIENTE_FK
FOREIGN KEY (PACIENTE_CODIGO)
REFERENCES PACIENTES(CODIGO);

-- ---------------------------------------------
-- INICIO DE LAS SECUENCIAS PARA LAS TABLAS  . -
-- ---------------------------------------------

-- SINTOMAS
DROP SEQUENCE SINTOMAS_SEQ;
CREATE SEQUENCE SINTOMAS_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER SINTOMAS_TRIGGER;
CREATE TRIGGER SINTOMAS_TRIGGER
BEFORE INSERT ON SINTOMAS
FOR EACH ROW
BEGIN
SELECT SINTOMAS_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- MOTIVOS
DROP SEQUENCE MOTIVOS_URGENCIA_SEQ;
CREATE SEQUENCE MOTIVOS_URGENCIA_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER MOTIVOS_URGENCIA_TRIGGER;
CREATE TRIGGER MOTIVOS_URGENCIA_TRIGGER
BEFORE INSERT ON MOTIVOS_URGENCIA
FOR EACH ROW
BEGIN
SELECT MOTIVOS_URGENCIA_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- CATEGORIAS
DROP SEQUENCE CATEGORIAS_SEQ;
CREATE SEQUENCE CATEGORIAS_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER CATEGORIAS_TRIGGER;
CREATE TRIGGER CATEGORIAS_TRIGGER
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
SELECT CATEGORIAS_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- MEDICAMENTOS
DROP SEQUENCE MEDICAMENTOS_SEQ;
CREATE SEQUENCE MEDICAMENTOS_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER MEDICAMENTOS_TRIGGER;
CREATE TRIGGER MEDICAMENTOS_TRIGGER
BEFORE INSERT ON MEDICAMENTOS
FOR EACH ROW
BEGIN
SELECT MEDICAMENTOS_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- SIGNOS
DROP SEQUENCE SIGNOS_SEQ;
CREATE SEQUENCE SIGNOS_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER SIGNOS_TRIGGER;
CREATE TRIGGER SIGNOS_TRIGGER
BEFORE INSERT ON SIGNOS
FOR EACH ROW
BEGIN
SELECT SIGNOS_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- CONSTANTES
DROP SEQUENCE CONSTANTES_SEQ;
CREATE SEQUENCE CONSTANTES_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER CONSTANTES_TRIGGER;
CREATE TRIGGER CONSTANTES_TRIGGER
BEFORE INSERT ON CONSTANTES
FOR EACH ROW
BEGIN
SELECT CONSTANTES_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- EPISODIOS DE TRIAJE
DROP SEQUENCE EPISODIOS_TRIAJE_SEQ;
CREATE SEQUENCE EPISODIOS_TRIAJE_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER EPISODIOS_TRIAJE_TRIGGER;
CREATE TRIGGER EPISODIOS_TRIAJE_TRIGGER
BEFORE INSERT ON EPISODIOS_TRIAJE
FOR EACH ROW
BEGIN
SELECT EPISODIOS_TRIAJE_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- DOCTORES
DROP SEQUENCE DOCTORES_SEQ;
CREATE SEQUENCE DOCTORES_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER DOCTORES_TRIGGER;
CREATE TRIGGER DOCTORES_TRIGGER
BEFORE INSERT ON DOCTORES
FOR EACH ROW
BEGIN
SELECT DOCTORES_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- ANTECEDENTES
DROP SEQUENCE ANTECEDENTES_SEQ;
CREATE SEQUENCE ANTECEDENTES_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER ANTECEDENTES_TRIGGER;
CREATE TRIGGER ANTECEDENTES_TRIGGER
BEFORE INSERT ON ANTECEDENTES
FOR EACH ROW
BEGIN
SELECT ANTECEDENTES_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- ALERGIAS
DROP SEQUENCE ALERGIAS_SEQ;
CREATE SEQUENCE ALERGIAS_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER ALERGIAS_TRIGGER;
CREATE TRIGGER ALERGIAS_TRIGGER
BEFORE INSERT ON ALERGIAS
FOR EACH ROW
BEGIN
SELECT ALERGIAS_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- PACIENTES
DROP SEQUENCE PACIENTES_SEQ;
CREATE SEQUENCE PACIENTES_SEQ 
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE;

DROP TRIGGER PACIENTES_TRIGGER;
CREATE TRIGGER PACIENTES_TRIGGER
BEFORE INSERT ON PACIENTES
FOR EACH ROW
BEGIN
SELECT PACIENTES_SEQ.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
END;
/

-- LLENADO DEL FMB
DECLARE
  T_SINTOMAS    		NUMBER;
  T_CONSTANTES	    	NUMBER;
  T_CATEGORIAS  	  	NUMBER;
  T_SIGNOS   			NUMBER;
  T_MOTIVOS_URGENCIA 	NUMBER;
  T_ALERGIAS  			NUMBER;

  -- TABLA SINTOMAS  
  C_INICIO_S			NUMBER;
  C_NIVEL		    	NUMBER;
  C_DURACION_S			NUMBER;
  C_REPETICION			NUMBER;
  
  -- TABLA CONSTANTES
  C_TEMP 				NUMBER;
  C_TAS        			NUMBER;
  C_FC     				NUMBER;
  C_FR 				 	NUMBER;
  C_SATO2      		 	NUMBER;
  C_GLICAP    			NUMBER;
  C_NIHSS				NUMBER;
  
  -- TABLA CATEGORIAS
  C_CATEGORIA 			NUMBER;
  
  -- TABLA SIGNOS
  C_TIPO_PIEL   		NUMBER;
  C_PULSO_RADIAL   		NUMBER;
  C_PULSO		   		NUMBER;
  C_RESPIRACION    		NUMBER;
  
  -- TABLA MOTIVOS_URGENCIA
  C_INICIO   			NUMBER;
  C_DURACION			NUMBER;

BEGIN

  -- OBTENER EL # DE OBJETO PARA LAS TABLAS CON COLUMNAS DIFUSAS:
  SELECT OBJECT_ID INTO T_SINTOMAS FROM USER_OBJECTS WHERE OBJECT_NAME='SINTOMAS';
  SELECT OBJECT_ID INTO T_CONSTANTES FROM USER_OBJECTS WHERE OBJECT_NAME='CONSTANTES';
  SELECT OBJECT_ID INTO T_CATEGORIAS FROM USER_OBJECTS WHERE OBJECT_NAME='CATEGORIAS';
  SELECT OBJECT_ID INTO T_SIGNOS   FROM USER_OBJECTS WHERE OBJECT_NAME='SIGNOS';
  SELECT OBJECT_ID INTO T_MOTIVOS_URGENCIA   FROM USER_OBJECTS WHERE OBJECT_NAME='MOTIVOS_URGENCIA';

  -- OBTENER EL # DE OBJETO PARA LAS COLUMNAS DIFUSAS:
  -- TABLA SINTOMAS
  SELECT COLUMN_ID INTO C_INICIO_S
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SINTOMAS' AND COLUMN_NAME='INICIOT';
	
  SELECT COLUMN_ID INTO C_NIVEL
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SINTOMAS' AND COLUMN_NAME='NIVELT';

  SELECT COLUMN_ID INTO C_DURACION_S
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SINTOMAS' AND COLUMN_NAME='DURACIONT';
	
  SELECT COLUMN_ID INTO C_REPETICION
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SINTOMAS' AND COLUMN_NAME='REPETICIONT';
	
  -- TABLA CONSTANTES
  SELECT COLUMN_ID INTO C_TEMP
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CONSTANTES' AND COLUMN_NAME='TEMPT';
	
  SELECT COLUMN_ID INTO C_TAS
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CONSTANTES' AND COLUMN_NAME='TAST';
	
  SELECT COLUMN_ID INTO C_FC
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CONSTANTES' AND COLUMN_NAME='FCT';
	
  SELECT COLUMN_ID INTO C_FR
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CONSTANTES' AND COLUMN_NAME='FRT';
		
  SELECT COLUMN_ID INTO C_SATO2
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CONSTANTES' AND COLUMN_NAME='SATO2';

  SELECT COLUMN_ID INTO C_GLICAP
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CONSTANTES' AND COLUMN_NAME='GLICAPT';

  SELECT COLUMN_ID INTO C_NIHSS
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CONSTANTES' AND COLUMN_NAME='NIHSST';
	
  -- TABLA CATEGORIAS
  SELECT COLUMN_ID INTO C_CATEGORIA
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CATEGORIAS' AND COLUMN_NAME='TIPO_CATEGORIAT';
	
  -- TABLA SIGNOS
  SELECT COLUMN_ID INTO C_TIPO_PIEL
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SIGNOS' AND COLUMN_NAME='TIPO_PIELT';

  SELECT COLUMN_ID INTO C_PULSO_RADIAL
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SIGNOS' AND COLUMN_NAME='PULSO_RADIALT';
  
  SELECT COLUMN_ID INTO C_PULSO
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SIGNOS' AND COLUMN_NAME='PULSOT';
  
  SELECT COLUMN_ID INTO C_RESPIRACION
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SIGNOS' AND COLUMN_NAME='RESPIRACIONT';

  -- TABLA MOTIVOS_CONSULTA
  SELECT COLUMN_ID INTO C_INICIO
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='MOTIVOS_URGENCIA' AND COLUMN_NAME='INICIOT';

  SELECT COLUMN_ID INTO C_DURACION
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME='MOTIVOS_URGENCIA' AND COLUMN_NAME='DURACIONT';
	
-- --------------------------------------------------------------------------------------   
  -- INFORMACIÓN DE LAS COLUMNAS DIFUSAS EN LA TABLA FUZZY COLUMN LIST
  INSERT INTO FCL VALUES (T_SINTOMAS,C_INICIO_S,2,1,USER||'.SINTOMAS.INICIO');
  INSERT INTO FCL VALUES (T_SINTOMAS,C_DURACION_S,2,1,USER||'.SINTOMAS.DURACION');
  INSERT INTO FCL VALUES (T_SINTOMAS,C_NIVEL,3,1,USER||'.SINTOMAS.NIVEL');
  INSERT INTO FCL VALUES (T_SINTOMAS,C_REPETICION,2,1,USER||'.SINTOMAS.REPETICION');  
  INSERT INTO FCL VALUES (T_CONSTANTES,C_TEMP,2,1,USER||'.CONSTANTES.TEMP');
  INSERT INTO FCL VALUES (T_CONSTANTES,C_TAS,2,1,USER||'.CONSTANTES.TAS');
  INSERT INTO FCL VALUES (T_CONSTANTES,C_FC,2,1,USER||'.CONSTANTES.FC');
  INSERT INTO FCL VALUES (T_CONSTANTES,C_FR,2,1,USER||'.CONSTANTES.FR');
  INSERT INTO FCL VALUES (T_CONSTANTES,C_SATO2,1,1,USER||'.CONSTANTES.SATO2');
  INSERT INTO FCL VALUES (T_CONSTANTES,C_GLICAP,2,1,USER||'.CONSTANTES.GLICAP');
  INSERT INTO FCL VALUES (T_CONSTANTES,C_NIHSS,2,1,USER||'.CONSTANTES.NIHSS');
  INSERT INTO FCL VALUES (T_CATEGORIAS,C_CATEGORIA,3,1,USER||'.CONSTANTES.CATEGORIA');
  INSERT INTO FCL VALUES (T_SIGNOS,C_TIPO_PIEL,3,1,USER||'.SIGNOS.TIPO_PIEL');
  INSERT INTO FCL VALUES (T_SIGNOS,C_PULSO_RADIAL,2,1,USER||'.SIGNOS.PULSO_RADIAL');
  INSERT INTO FCL VALUES (T_SIGNOS,C_PULSO,2,1,USER||'.SIGNOS.PULSO');
  INSERT INTO FCL VALUES (T_SIGNOS,C_RESPIRACION,2,1,USER||'.SIGNOS.RESPIRACION');
  INSERT INTO FCL VALUES (T_MOTIVOS_URGENCIA,C_INICIO,2,1,USER||'.MOTIVOS_URGENCIA.INICIO');
  INSERT INTO FCL VALUES (T_MOTIVOS_URGENCIA,C_DURACION,1,1,USER||'.MOTIVOS_URGENCIA.DURACION');
  
    -- COMPATIBILIDAD DE ATRIBUTOS TIPO 3:
  -- POR AHORA NO EXISTE COMPATIBILIDAD ENTRE ATRIBUTOS
  -- INSERT INTO FCC VALUES (T_NOMBRETABLA,C_NOMBRECOLUMNA,T_NOMBRETABLA,C_NOMBRECOLUMNA);
  
-- --------------------------------------------------------------------------------------  
  -- INFORMACIÓN DE LAS ETIQUETAS QUE SE ALMACENARAN EN LAS COLUMNAS DIFUSAS, FUZZY OBJECT LIST
  -- TIPO 0 INDICA QUE ES UN PREDICADO DE LA COLUMNA,
  -- 1 QUE ESTA REFERENCIADA EN LA TABLA DE CERCANIAS Y
  -- 4 QUE ES UN CUANTIFICADOR ABSOLUTO
  
  -- TABLA SINTOMAS
  INSERT INTO FOL VALUES (T_SINTOMAS,C_INICIO_S,0,'HACE_POCO',0);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_INICIO_S,1,'MAS_O_MENOS',0);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_INICIO_S,2,'HACE_MUCHO',0);
  
  INSERT INTO FOL VALUES (T_SINTOMAS,C_NIVEL,0,'LIGERO',1);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_NIVEL,1,'MODERADO',1);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_NIVEL,2,'INTENSO',1);

  INSERT INTO FOL VALUES (T_SINTOMAS,C_DURACION_S,0,'POCO',0);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_DURACION_S,1,'MAS_O_MENOS',0);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_DURACION_S,2,'MUCHO',0);  
  
  INSERT INTO FOL VALUES (T_SINTOMAS,C_REPETICION,0,'POCO',0);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_REPETICION,1,'MAS_O_MENOS',0);
  INSERT INTO FOL VALUES (T_SINTOMAS,C_REPETICION,2,'MUCHO',0);  
  
  -- TABLA CONSTANTES
  INSERT INTO FOL VALUES (T_CONSTANTES,C_TEMP,0,'BAJA',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_TEMP,1,'NORMAL',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_TEMP,2,'FIEBRE',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_TEMP,3,'FIEBRE_MUY_ALTA',0);
  
  INSERT INTO FOL VALUES (T_CONSTANTES,C_TAS,0,'MUY_BAJA',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_TAS,1,'NORMAL',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_TAS,2,'MUY_ALTA',0);
  
  INSERT INTO FOL VALUES (T_CONSTANTES,C_FC,0,'MUY_BAJA',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_FC,1,'NORMAL',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_FC,2,'MUY_ALTA',0);

  INSERT INTO FOL VALUES (T_CONSTANTES,C_FR,0,'BRADIPNEA',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_FR,1,'NORMAL',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_FR,2,'TAQUIPNEA',0);
  
  INSERT INTO FOL VALUES (T_CONSTANTES,C_SATO2,0,'MUY_BAJA',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_SATO2,1,'NORMAL',0);
  
  INSERT INTO FOL VALUES (T_CONSTANTES,C_GLICAP,0,'HIPOGLUCEMIA',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_GLICAP,1,'NORMAL',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_GLICAP,2,'GLUCOSA_ALTERADA_EN_AYUNO',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_GLICAP,3,'HIPERGLUCEMIA',0);
  
  INSERT INTO FOL VALUES (T_CONSTANTES,C_NIHSS,0,'ALERTA',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_NIHSS,1,'CONFUSO',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_NIHSS,2,'LETARGICO',0);
  INSERT INTO FOL VALUES (T_CONSTANTES,C_NIHSS,3,'COMA_PROFUNDO',0);
  
  -- TABLA CATEGORIAS
  INSERT INTO FOL VALUES (T_CATEGORIAS,C_CATEGORIA,0,'HEMORRAGIA',1);
  INSERT INTO FOL VALUES (T_CATEGORIAS,C_CATEGORIA,1,'HIPERTENSION',1);
  INSERT INTO FOL VALUES (T_CATEGORIAS,C_CATEGORIA,2,'DIABETICO',1);
  INSERT INTO FOL VALUES (T_CATEGORIAS,C_CATEGORIA,3,'TRAUMATISMO',1);
  INSERT INTO FOL VALUES (T_CATEGORIAS,C_CATEGORIA,4,'NORMAL',1);
  
  -- TABLA SIGNOS
  INSERT INTO FOL VALUES (T_SIGNOS,C_TIPO_PIEL,0,'PIEL_FRIA_Y_PALIDA',1);
  INSERT INTO FOL VALUES (T_SIGNOS,C_TIPO_PIEL,1,'SUDADA_Y_CALIENTE',1);
  INSERT INTO FOL VALUES (T_SIGNOS,C_TIPO_PIEL,2,'MUY_CALIENTE',1);
  INSERT INTO FOL VALUES (T_SIGNOS,C_TIPO_PIEL,3,'NORMAL',1);
  
  INSERT INTO FOL VALUES (T_SIGNOS,C_PULSO_RADIAL,0,'FALTA',0);
  INSERT INTO FOL VALUES (T_SIGNOS,C_PULSO_RADIAL,1,'DEBIL',0);
  INSERT INTO FOL VALUES (T_SIGNOS,C_PULSO_RADIAL,2,'NORMAL',0);
  INSERT INTO FOL VALUES (T_SIGNOS,C_PULSO_RADIAL,3,'FUERTE',0);
  
  INSERT INTO FOL VALUES (T_SIGNOS,C_PULSO,0,'BRADICARDIA',0);
  INSERT INTO FOL VALUES (T_SIGNOS,C_PULSO,1,'NORMAL',0);
  INSERT INTO FOL VALUES (T_SIGNOS,C_PULSO,2,'TAQUICARDIA',0);

  INSERT INTO FOL VALUES (T_SIGNOS,C_RESPIRACION,0,'LENTA_Y_PROFUNDA',0);
  INSERT INTO FOL VALUES (T_SIGNOS,C_RESPIRACION,1,'NORMAL',0);
  INSERT INTO FOL VALUES (T_SIGNOS,C_RESPIRACION,2,'SUPERFICIAL_Y_RAPIDA',0);

  -- TABLA MOTIVOS DE URGENCIA
  INSERT INTO FOL VALUES (T_MOTIVOS_URGENCIA,C_INICIO,0,'HACE_POCO',0);
  INSERT INTO FOL VALUES (T_MOTIVOS_URGENCIA,C_INICIO,1,'MAS_O_MENOS',0);
  INSERT INTO FOL VALUES (T_MOTIVOS_URGENCIA,C_INICIO,2,'HACE_MUCHO',0);
  
  INSERT INTO FOL VALUES (T_MOTIVOS_URGENCIA,C_DURACION,0,'POCO',0);
  INSERT INTO FOL VALUES (T_MOTIVOS_URGENCIA,C_DURACION,1,'MAS_O_MENOS',0);
  INSERT INTO FOL VALUES (T_MOTIVOS_URGENCIA,C_DURACION,2,'MUCHO',0);
  
  -- TABLA ALERGIAS
  -- FALTAN LAS ALERGIAS
  
-- --------------------------------------------------------------------------------------  
  -- INFORMACIÓN DE LOS VALORES QUE CORRESPONDEN A LAS ETIQUETAS, FUZZY LABEL DEFINITION
  -- POR AHORA, LOS VALORES DE LA INICIO SE MANEJA EN HORAS, LA DURACIÓN ESTA EXPRESADA EN MINUTOS
  -- TABLA SINTOMAS
  INSERT INTO FLD VALUES (T_SINTOMAS,C_INICIO_S,0,0,1,14,24);
  INSERT INTO FLD VALUES (T_SINTOMAS,C_INICIO_S,1,15,30,72,96);
  INSERT INTO FLD VALUES (T_SINTOMAS,C_INICIO_S,2,84,96,10000,10001);
  
  INSERT INTO FLD VALUES (T_SINTOMAS,C_DURACION_S,0,0,1,5,10);
  INSERT INTO FLD VALUES (T_SINTOMAS,C_DURACION_S,1,8,15,25,28);
  INSERT INTO FLD VALUES (T_SINTOMAS,C_DURACION_S,2,25,30,10000,10001);
  
  -- LA REPETICION MIDE EN CUANTAS VECES POR DIA REPITE EL SINTOMA
  INSERT INTO FLD VALUES (T_SINTOMAS,C_REPETICION,0,0,1,5,10);
  INSERT INTO FLD VALUES (T_SINTOMAS,C_REPETICION,1,6,8,12,15);
  INSERT INTO FLD VALUES (T_SINTOMAS,C_REPETICION,2,10,12,10000,10001);  
  
  -- TABLA CONSTANTES
  INSERT INTO FLD VALUES (T_CONSTANTES,C_TEMP,0,0,1,36,37);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_TEMP,1,35,37,38,40);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_TEMP,2,38,40,41,42);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_TEMP,3,41,42,10000,10001);
  
  INSERT INTO FLD VALUES (T_CONSTANTES,C_TAS,0,0,1,90,110); -- HIPOTENSION
  INSERT INTO FLD VALUES (T_CONSTANTES,C_TAS,1,90,95,180,200);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_TAS,2,160,200,10000,10001); -- HIPERTENSION
  
  INSERT INTO FLD VALUES (T_CONSTANTES,C_FC,0,0,1,40,45);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_FC,1,40,45,120,126);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_FC,2,120,125,10000,10001);

  INSERT INTO FLD VALUES (T_CONSTANTES,C_FR,0,0,1,10,13); -- 'BRADIPNEA',1);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_FR,1,10,11,29,31); -- 'NORMAL',1);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_FR,2,26,30,10000,10001); -- 'TAQUIPNEA',1);
  
  INSERT INTO FLD VALUES (T_CONSTANTES,C_SATO2,0,0,1,92,93);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_SATO2,1,92,93,1000,1001);
  
  INSERT INTO FLD VALUES (T_CONSTANTES,C_GLICAP,0,0,1,69,73);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_GLICAP,1,68,70,99,105);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_GLICAP,2,98,100,124,126);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_GLICAP,3,124,126,10000,10001);
  
/*
  NIHSS NO DEBE SER UN ATRIBUTO DIFUSO TIPO 2, POSIBLEMENTE SEA TIPO 4 O 3.
*/
  INSERT INTO FLD VALUES (T_CONSTANTES,C_NIHSS,0,0,1,2,3);     -- ALERTA
  INSERT INTO FLD VALUES (T_CONSTANTES,C_NIHSS,1,3,4,5,6);     --'CONFUSO',0);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_NIHSS,2,6,7,8,9);     -- LETARGICO',0);
  INSERT INTO FLD VALUES (T_CONSTANTES,C_NIHSS,3,9,10,100,1001);  -- 'COMA_PROFUNDO',0);

  -- TABLA SIGNOS
/*
  PARECE SER UN ATRIBUTO DIFUSO TIPO 3 O 4
*/
  INSERT INTO FLD VALUES (T_SIGNOS,C_PULSO_RADIAL,0,1,2,3,4);     -- 'FALTA',1);
  INSERT INTO FLD VALUES (T_SIGNOS,C_PULSO_RADIAL,1,4,5,6,7);     -- 'DEBIL',1);
  INSERT INTO FLD VALUES (T_SIGNOS,C_PULSO_RADIAL,2,7,8,9,10); -- 'NORMAL',1);
  INSERT INTO FLD VALUES (T_SIGNOS,C_PULSO_RADIAL,3,10,11,100,1001);    -- 'FUERTE',1);
  
  INSERT INTO FLD VALUES (T_SIGNOS,C_PULSO,0,0,1,50,51); 
  INSERT INTO FLD VALUES (T_SIGNOS,C_PULSO,1,50,51,119,122); 
  INSERT INTO FLD VALUES (T_SIGNOS,C_PULSO,2,115,120,10000,10001); -- 'NORMAL',1);

  INSERT INTO FLD VALUES (T_SIGNOS,C_RESPIRACION,0,0,1,2,3); 
  INSERT INTO FLD VALUES (T_SIGNOS,C_RESPIRACION,1,3,4,5,6); 
  INSERT INTO FLD VALUES (T_SIGNOS,C_RESPIRACION,2,6,7,100,1001); 

  -- TABLA MOTIVOS_URGENCIA
  INSERT INTO FLD VALUES (T_MOTIVOS_URGENCIA,C_INICIO,0,0,8,18,24);
  INSERT INTO FLD VALUES (T_MOTIVOS_URGENCIA,C_INICIO,1,20,48,72,96);
  INSERT INTO FLD VALUES (T_MOTIVOS_URGENCIA,C_INICIO,2,84,96,10000,10001);  
  
  INSERT INTO FLD VALUES (T_MOTIVOS_URGENCIA,C_DURACION,0,0,1,5,10);
  INSERT INTO FLD VALUES (T_MOTIVOS_URGENCIA,C_DURACION,1,8,15,25,28);
  INSERT INTO FLD VALUES (T_MOTIVOS_URGENCIA,C_DURACION,2,25,30,10000,10001); 

-- --------------------------------------------------------------------------------------  
-- FUZZY APROXIMITY MUCH
	INSERT INTO FAM VALUES (T_SINTOMAS,C_INICIO_S,8,32);
	INSERT INTO FAM VALUES (T_MOTIVOS_URGENCIA,C_INICIO,8,32);
	INSERT INTO FAM VALUES (T_SINTOMAS,C_DURACION_S,3,15);
	INSERT INTO FAM VALUES (T_MOTIVOS_URGENCIA,C_DURACION,3,15);
	INSERT INTO FAM VALUES (T_SINTOMAS,C_REPETICION,3,15);	 
	INSERT INTO FAM VALUES (T_CONSTANTES,C_TEMP,2,5);  
	INSERT INTO FAM VALUES (T_CONSTANTES,C_TAS,15,40);
	INSERT INTO FAM VALUES (T_CONSTANTES,C_FC,10,40);
	INSERT INTO FAM VALUES (T_CONSTANTES,C_FR,5,15);
	INSERT INTO FAM VALUES (T_CONSTANTES,C_GLICAP,10,30);
	INSERT INTO FAM VALUES (T_SIGNOS,C_PULSO,10,30);	 
	INSERT INTO FAM VALUES (T_SIGNOS,C_RESPIRACION,1,10);  

-- --------------------------------------------------------------------------------------  
-- FUZZY NEARNESS DEFINITION
-- LA ESCALA DE NIVEL SE TRATA DENTRO DE LA TABLA FUZZY NEARNESS DEFINITION
  INSERT INTO FND VALUES (T_SINTOMAS,C_NIVEL,0,1,0.5);
  INSERT INTO FND VALUES (T_SINTOMAS,C_NIVEL,0,2,0);
  INSERT INTO FND VALUES (T_SINTOMAS,C_NIVEL,1,2,0.5);
  
-- LAS CATEGORIAS DENTRO DE LA FUZZY NEARNESS DEFINITION  
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,0,1,0.3);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,0,2,0.5);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,0,3,0.8);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,0,4,0);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,1,2,0.8);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,1,3,0.1);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,1,4,0);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,2,3,0.3);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,2,4,0);
  INSERT INTO FND VALUES (T_CATEGORIAS,C_CATEGORIA,3,4,0);

  INSERT INTO FND VALUES (T_SIGNOS,C_TIPO_PIEL,0,1,0.15);  
  INSERT INTO FND VALUES (T_SIGNOS,C_TIPO_PIEL,0,2,0.10);  
  INSERT INTO FND VALUES (T_SIGNOS,C_TIPO_PIEL,0,3,0.25);  
  INSERT INTO FND VALUES (T_SIGNOS,C_TIPO_PIEL,1,2,0.60);  
  INSERT INTO FND VALUES (T_SIGNOS,C_TIPO_PIEL,1,3,0.25);  
  INSERT INTO FND VALUES (T_SIGNOS,C_TIPO_PIEL,2,3,0.25);  
  
  -- CREACIÓN DE LOS SINONIMOS DE LAS TABLAS DEL SISTEMA PARA QUE EL USUARIO SYSTEM PUEDA 
  -- USARLAS COMO SI FUESEN PROPIAS
  
  COMMIT;
  END;
/   